(() => {
  const refs={
    treehouse:[["🐌","Улитка","Она появляется по всей Земле Ууу. Фанаты знают: если заметил её, значит смотрел внимательно.",12,68],["📕","Энхиридион","Книга для настоящих героев. В этой игре потерялись именно её страницы.",84,48],["⚔️","Меч героя","Один из тех предметов, которые Финн менял подозрительно часто.",73,71],["🥪","Запас приключенца","Исследовать Ууу на пустой желудок крайне непрофессионально.",31,80]],
    candy:[["🐌","Улитка","Даже среди конфет она каким-то образом не становится десертом.",11,74],["🧪","Лаборатория","Бубльгум умеет превратить обычный вторник в научный эксперимент.",74,37],["🍬","Конфетный народ","Основной ресурс королевства: сахар, оптимизм и периодические катастрофы.",88,70],["🧛","Странный интерес Мятного Лакея","С ним лучше не спрашивать, почему дверь в подвал заперта.",20,53]],
    forest:[["🐌","Улитка","Она снова здесь. Да, это уже коллекционная охота.",10,73],["🍎","Яблоки Деревяшки","Некоторые вещи во вселенной стабильны. Например, любовь Деревяшки к яблокам.",57,42],["🪄","Волшебный Человек","Если что-то в лесу стало абсурдным, подозрение автоматически падает на него.",73,58],["🗿","След старого мира","Земля Ууу хранит гораздо больше прошлого, чем кажется на первый взгляд.",83,75]],
    marceline:[["🐌","Улитка","Улитка не боится ни вампиров, ни бас-гитары.",10,72],["🎸","Бас Марселин","Самый узнаваемый музыкальный предмет этой части Ууу.",74,66],["🧸","Хамбо","Старая игрушка может оказаться важнее целого сундука сокровищ.",19,57],["🦇","Летучая мышь","Иногда самый простой способ попасть куда-то — перестать быть человеком.",87,39]],
    ice:[["🐌","Улитка","Поразительно, но она не замёрзла. Сценарная броня работает.",10,73],["👑","Корона","Очень могущественный предмет и очень плохой вариант зимней шапки.",78,44],["🐧","Пингвины","Когда их много, поиск одного Гюнтера становится отдельным видом спорта.",85,72],["❄️","Лёд","Ледяной Король практически построил из него личный бренд.",19,49]],
    fire:[["🐌","Улитка","Здесь ей уже действительно жарковато.",10,73],["🔥","Огненные люди","Вопрос пожарной безопасности в королевстве давно признан бессмысленным.",85,72],["💎","Кристалл","Подозрительно сияет. Следовательно, на него обязательно надо нажать.",76,43],["🍥","Коричный Булочка","Один из немногих персонажей, способных выглядеть уместно сразу в двух королевствах.",18,54]],
    lemon:[["🐌","Улитка","Её присутствие официально НЕ РЕГУЛИРУЕТСЯ.",10,73],["🍋","Лимоны","Семь нормально. Восемь, разумеется, НЕДОПУСТИМО.",84,70],["📏","Порядок","Лемонграб уверен, что мир станет лучше, если всё разложить по линейке.",77,44],["🎺","Громкость","Этот замок можно было бы найти по звуку даже без карты.",20,55]],
    wilds:[["🐌","Улитка","Даже легендарные земли не обходятся без неё.",10,73],["🗿","Древние руины","Ууу построена поверх мира, который когда-то выглядел совсем иначе.",55,44],["⚔️","Героическое наследие","Билли напоминает, что до Финна герои уже успели натворить немало легенд.",80,57],["🌾","Дальние земли","Хорошее место для персонажей, которым не хватило места в остальных сценах.",24,76]],
    prismo:[["🐌","Улитка","Даже между реальностями. Просто прими это.",10,73],["🥒","Соленья","У Призмо довольно земные вкусы для существа такого масштаба.",82,72],["🦉","Космическая Сова","Если она появилась во сне, утро может стать сильно интереснее.",74,42],["✨","Желание","Формулировать желания надо так, будто договор читает особенно вредный юрист.",22,52]]
  };

  function ensureUi(){
    const actions=document.querySelector('.hud-actions');
    if(actions&&!document.getElementById('musicBtn')){
      const music=document.createElement('button');music.id='musicBtn';music.className='icon-btn';music.textContent='♫';music.title='Музыка';
      const sound=document.createElement('button');sound.id='soundBtn';sound.className='icon-btn';sound.textContent='🔊';sound.title='Звуки';
      actions.prepend(sound);actions.prepend(music);
      music.onclick=()=>{AT_AUDIO.toggleMusic();AT_AUDIO.play('click')};sound.onclick=()=>{AT_AUDIO.toggleSound();AT_AUDIO.play('click')};
    }
    const hc=document.querySelector('.hud-center');if(hc&&!document.getElementById('saveBadge')){const b=document.createElement('div');b.id='saveBadge';b.className='save-badge';b.textContent='💾 сохранено';hc.appendChild(b)}
    const pages=document.querySelector('.pages');if(pages&&!document.getElementById('refCounter')){const r=document.createElement('span');r.id='refCounter';r.className='ref-counter';pages.appendChild(r)}
    AT_AUDIO.syncButtons();
  }
  function pulseSave(){const b=document.getElementById('saveBadge');if(!b)return;b.classList.remove('pulse');void b.offsetWidth;b.classList.add('pulse')}
  const baseSave=save;save=function(){baseSave();pulseSave();updateRefCounter()};
  const baseGive=give;give=function(id){const had=has(id);baseGive(id);if(!had)AT_AUDIO.play('pickup')};
  const baseComplete=complete;complete=function(id,label){const had=state.pages.includes(id);baseComplete(id,label);if(!had)AT_AUDIO.play('page')};
  function updateRefCounter(){const el=document.getElementById('refCounter');if(el)el.textContent=` • пасхалки ${(state.flags.refs||[]).length}/${Object.values(refs).flat().length}`}

  function addReferences(id){
    if(!refs[id])return;const found=state.flags.refs||[];
    refs[id].forEach((r,i)=>{const key=`${id}:${i}`,b=document.createElement('button');b.className='reference-hotspot'+(found.includes(key)?' found':'');b.style.setProperty('--rx',r[3]+'%');b.style.setProperty('--ry',r[4]+'%');b.innerHTML=`<span>${r[0]}</span>`;b.title=r[1];
      b.onclick=()=>{AT_AUDIO.play('magic');state.flags.refs=state.flags.refs||[];if(!state.flags.refs.includes(key)){state.flags.refs.push(key);save()}openModal(`<div class="reference-card"><div class="reference-big">${r[0]}</div><div><div class="game-title">${r[1]}</div><p>${r[2]}</p><small>Пасхалка найдена • прогресс сохранён автоматически</small></div></div>`)};sceneDecor.appendChild(b)});
  }

  renderScene=function(){
    let s=SCENES[state.scene];if(s.locked&&s.locked()){state.scene='treehouse';s=SCENES.treehouse}
    scene.style.setProperty('--sky1',s.colors[0]);scene.style.setProperty('--sky2',s.colors[1]);scene.style.setProperty('--ground1',s.colors[2]);scene.style.setProperty('--ground2',s.colors[3]);scene.dataset.scene=state.scene;
    sceneKicker.textContent=s.kicker;sceneTitle.textContent=s.title;sceneDescription.textContent=s.desc;sceneDecor.innerHTML=AT_ART.sceneArt(state.scene);hotspots.innerHTML='';
    s.people.forEach(([id,x,y])=>addCharacter(id,x,y));s.objects.forEach(([id,icon,label,x,y])=>addObject(id,icon,label,x,y));addReferences(state.scene);AT_AUDIO.setScene(state.scene);updateHud();updateRefCounter();ensureUi();
  };
  addCharacter=function(id,x,y){const[name]=CHAR[id],b=document.createElement('button');b.className='hotspot art-hotspot'+(state.completed[id]?' done':'');b.style.setProperty('--x',x+'%');b.style.setProperty('--y',y+'%');b.innerHTML=`<div class="character-art">${AT_ART.characterArt(id)}</div><div class="hotspot-label">${name}</div>`;b.onclick=()=>{AT_AUDIO.play(id==='gunter'?'gunter':'pop');talk(id)};hotspots.appendChild(b)};
  addObject=function(id,icon,label,x,y){const b=document.createElement('button');b.className='hotspot object art-object';b.style.setProperty('--x',x+'%');b.style.setProperty('--y',y+'%');b.innerHTML=`<div class="object-art">${AT_ART.itemArt(id)}</div><div class="hotspot-label">${label}</div>`;b.onclick=()=>{AT_AUDIO.play('click');inspectObject(id)};hotspots.appendChild(b)};
  showDialog=function(id,text,actions=[]){const[name]=CHAR[id];openModal(`<div class="dialog-head illustrated"><div class="portrait-art">${AT_ART.characterArt(id)}</div><div><div class="dialog-name">${name}</div><div class="dialog-sub">${SCENES[state.scene].title}</div></div></div><div class="dialog-text">${text}</div><div id="dialogActions" class="dialog-actions"></div><div class="note">Некоммерческая фан-игра. Прогресс сохраняется автоматически в этом браузере.</div>`);const box=document.getElementById('dialogActions');actions.forEach(a=>{const b=document.createElement('button');b.className='dialog-btn'+(a.primary?' primary':'')+(a.danger?' danger':'');b.textContent=a.label;b.onclick=()=>{AT_AUDIO.play('click');a.run()};box.appendChild(b)})};

  SCENES.prismo.locked=()=>false;
  const baseTalk=talk;talk=function(id){if(id==='bmo'&&!has('cartridge'))state.inventory.push('cartridge');if(id==='pb'&&!has('candycoil'))state.inventory.push('candycoil');if(id==='marceline'&&!has('basspick'))state.inventory.push('basspick');if(id==='jake'&&!has('stretchy'))state.inventory.push('stretchy');if(['bmo','pb','marceline','jake'].includes(id))save();baseTalk(id)};

  startMemory=function(){const symbols=['🐌','⚔️','👑','🐌','⚔️','👑'].sort(()=>Math.random()-.5);gameShell('🎮 Игра БиМО','Найди всего три пары картинок.',`<div id="memoryGrid" class="memory-grid kid-memory"></div>`);let first=null,lock=false,matched=0;symbols.forEach(s=>{const b=document.createElement('button');b.className='memory-card';b.textContent=s;b.onclick=()=>{if(lock||b.classList.contains('matched')||b===first)return;AT_AUDIO.play('click');b.classList.add('open');if(!first){first=b;return}if(first.textContent===b.textContent){first.classList.add('matched');b.classList.add('matched');matched+=2;first=null;AT_AUDIO.play('success');if(matched===symbols.length)success('bmo','Память','БиМО объявляет тебя чемпионом игровых картриджей.')}else{lock=true;const a=first;first=null;AT_AUDIO.play('wrong');setTimeout(()=>{a.classList.remove('open');b.classList.remove('open');lock=false},450)}};memoryGrid.appendChild(b)})};
  startLab=function(){gameShell('🧪 Лаборатория Бубльгум','Нажми на компонент, который лучше всего подходит к конфетной энергии.',`<div id="labGrid" class="lab-grid"></div>`);[['🍬','Сахар',true],['🪨','Камень',false],['🧦','Носок',false]].forEach(([icon,label,ok])=>{const b=document.createElement('button');b.className='lab-choice big-choice';b.innerHTML=`<b>${icon}</b><span>${label}</span>`;b.onclick=()=>{if(ok){AT_AUDIO.play('success');success('pb','Наука','Бубльгум получает идеальную конфетную энергию.')}else{AT_AUDIO.play('wrong');gameStatus.textContent='Почти. Выбери самый сладкий вариант.'}};labGrid.appendChild(b)})};
  startSimon=function(){gameShell('🎸 Музыка Марселин','Марселин покажет две ноты. Просто повтори их.',`<div id="simonRow" class="simon-row"></div><button id="simonStart" class="game-btn primary">Показать ноты</button>`);const colors=['#e86a72','#65b3df','#ebcb56'];let seq=[],input=[],busy=false;colors.forEach((c,i)=>{const b=document.createElement('button');b.className='simon-pad';b.style.background=c;b.onclick=()=>{if(busy||seq.length===0)return;input.push(i);flash(b);AT_AUDIO.play('click');const k=input.length-1;if(input[k]!==seq[k]){input=[];AT_AUDIO.play('wrong');gameStatus.textContent='Ничего страшного. Послушай ещё раз.';return}if(input.length===seq.length){AT_AUDIO.play('success');success('marceline','Музыка','Марселин одобряет короткий, но мощный рифф.')}};simonRow.appendChild(b)});function flash(b){b.classList.add('flash');setTimeout(()=>b.classList.remove('flash'),260)}simonStart.onclick=async()=>{busy=true;seq=[Math.floor(Math.random()*3),Math.floor(Math.random()*3)];input=[];gameStatus.textContent='Смотри...';for(const i of seq){await new Promise(r=>setTimeout(r,360));flash(simonRow.children[i]);AT_AUDIO.play('pop')}setTimeout(()=>{busy=false;gameStatus.textContent='Теперь повтори две ноты.'},300)}};
  startPenguins=function(){gameShell('🐧 Найди Гюнтера','Настоящий Гюнтер в короне. Тут без подвоха, просто тыкни в него.',`<div id="penguinGrid" class="penguin-grid"></div>`);const real=Math.floor(Math.random()*6);for(let i=0;i<6;i++){const b=document.createElement('button');b.className='penguin';b.textContent=i===real?'🐧👑':'🐧';b.onclick=()=>{if(i===real){AT_AUDIO.play('gunter');success('iceking','Пингвины','Гюнтер найден. Венк.')}else{AT_AUDIO.play('wrong');b.disabled=true;b.style.opacity=.35;gameStatus.textContent='Не этот. Попробуй другого, попытки не ограничены.'}};penguinGrid.appendChild(b)}};
  startOrder=function(){gameShell('🍋 Порядок Лемонграба','Нажми всего три картинки: лимон → корона → книга.',`<div id="orderRow" class="order-row"></div>`);const target=['🍋','👑','📖'],pool=[...target].sort(()=>Math.random()-.5),picked=[];pool.forEach(sym=>{const b=document.createElement('button');b.className='order-token';b.textContent=sym;b.onclick=()=>{if(b.disabled)return;if(sym!==target[picked.length]){AT_AUDIO.play('wrong');gameStatus.textContent='НЕДОПУСТИМО! Но можно сразу попробовать ещё раз.';picked.splice(0);[...orderRow.children].forEach(x=>{x.disabled=false;x.style.opacity=1});return}AT_AUDIO.play('click');picked.push(sym);b.disabled=true;b.style.opacity=.35;if(picked.length===target.length)success('lemongrab','Порядок','Лемонграб молчит две секунды. Невероятный успех.')};orderRow.appendChild(b)})};
  startFire=function(){gameShell('🔥 Огненный кристалл','Один раз останови указатель в большой жёлтой зоне.',`<div class="fire-meter kid-fire"><div id="firePointer" class="fire-pointer"></div></div><button id="fireStop" class="game-btn primary">СТОП</button>`);let pos=3,dir=1;const timer=setInterval(()=>{pos+=dir*2;if(pos>=98){pos=98;dir=-1}if(pos<=2){pos=2;dir=1}firePointer.style.left=pos+'%'},34);fireStop.onclick=()=>{if(pos>=25&&pos<=75){clearInterval(timer);AT_AUDIO.play('success');success('flame','Огонь','Кристалл стабилен. Принцесса Пламя довольна.')}else{AT_AUDIO.play('wrong');gameStatus.textContent='Чуть мимо. Жёлтая зона большая, попробуй ещё раз.'}}};
  startStretch=function(){gameShell('🟡 Джейк растягивается','Просто нажми на зелёную цель. Джейк сам дотянется.',`<div class="jake-simple"><div class="jake-line">🟡〰️〰️〰️🟢</div><button id="jakeGoal" class="game-btn primary">Дотянуться!</button></div>`);jakeGoal.onclick=()=>{AT_AUDIO.play('success');success('jake','Гибкость','Джейк дотянулся. Для него это был скорее разогрев.')}};
  startPrismo=function(){gameShell('✨ Желание Призмо','Какое желание звучит безопаснее?',`<div id="triviaOptions" class="trivia-options"></div>`);[['Хочу вернуть потерянные страницы на место.',true],['Хочу вообще всё на свете!',false],['Пусть книги исчезнут.',false]].forEach(([text,ok])=>{const b=document.createElement('button');b.className='trivia-option';b.textContent=text;b.onclick=()=>{if(ok){AT_AUDIO.play('magic');success('prismo','Желание','Призмо одобряет. Коротко и без разрушения реальности.')}else{AT_AUDIO.play('wrong');gameStatus.textContent='Призмо качает головой. Попробуй более спокойное желание.'}};triviaOptions.appendChild(b)})};

  ensureUi();updateRefCounter();renderScene();
})();